---
- hosts: aws
  become: Yes
  tasks:
    - name: Installs nginx web server
      yum: name=httpd state=installed update_cache=true
      notify:
        - start nginx
  handlers:
    - name: start nginx
      service: name=httpd state=started

